### ISSUE TITLE
trigger onclick on label using toggle

### ISSUE THREAD

**Issue by ghoshorn** [guidone/lets-form#53]
When using Letsform+Antd toggle(Switch), I would expect to toggle the value only when clicking on the toggle button. But now clicking on the toggle label will also trigger the onClick event.

Like
`{
    name: 'toggle_test',
    label: 'this is a toggle',
    component: 'toggle',
    row: false,
  },` Clicking on the `this is a toggle` will also change the value.

BTW, toggle widget is missing in the 'Designer' list.

**Comment by guidone** [comment]
Hi @ghoshorn 

1. I believe this is the intended behaviour in Antd, read [here](https://github.com/ant-design/ant-design/issues/51499) and [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label), the Switch component (Toggle in LetsForm) is used in idiomatic way (for AntD), see [here](https://ant.design/components/form, but yes in this example, clicking on label does nothing).
2. What do you mean the toggle is missing in the designer list?
3. You can specify the fields alignment in the form settings

<img width="1372" alt="image" src="https://github.com/user-attachments/assets/57e8c9e7-23b5-4fca-a255-48c54a98c577">

But ofc this will affect all fields, if you want this alignment just for the toggle field, since there's not idiomatic way to do this in AntD (see [here](https://ant.design/components/switch)), you can

1. in the `toggle` component set label to blank
2. create a `columns` component with two columns, first column width 0, secondo column width 1, move the `toggle` component to first column
3. put a `placeholder` component in the second column (it will be your label)

<img width="1420" alt="image" src="https://github.com/user-attachments/assets/d0cb5ccd-3714-479a-88cf-c58d1a693923">
